# Generated by Django 4.1.2 on 2022-10-18 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTM', '0003_alter_profile_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
        migrations.AlterField(
            model_name='workexp',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 10, 18)),
        ),
    ]
