# Generated by Django 4.1.2 on 2022-10-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTM', '0004_remove_profile_id_user_alter_workexp_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.CharField(max_length=10),
        ),
    ]
