# Generated by Django 4.1.2 on 2022-10-18 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FTM', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FTM.profile'),
        ),
        migrations.AlterField(
            model_name='workexp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FTM.profile'),
        ),
    ]
