# Generated by Django 4.1.2 on 2022-10-19 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTM', '0006_alter_reviews_user_alter_workexp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexp',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 10, 19)),
        ),
    ]
