# Generated by Django 4.1.2 on 2022-10-20 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTM', '0012_alter_profile_user_alter_reviews_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexp',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 10, 20)),
        ),
    ]
