# Generated by Django 4.1.2 on 2022-10-21 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTM', '0013_alter_workexp_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexp',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 10, 21)),
        ),
    ]
