# Generated by Django 4.1.2 on 2022-10-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTM', '0016_alter_workexp_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ManyToManyField(null=True, related_name='request', to='FTM.profile')),
            ],
        ),
    ]
