# Generated by Django 4.1.2 on 2022-11-01 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FTM', '0018_friendlist_friendrequest_delete_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
